spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3306/board?serverTimezone=Asia/Seoul
    username: boardUser
    password: 1a2s3d4f!

  thymeleaf:
    prefix: classpath:/static/
    suffix: .html

  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher